[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

["x11-libs/xcb-imdkit"]
source = "github"
github = "fcitx/xcb-imdkit"
use_latest_tag = true

["app-i18n/libime"]
source = "github"
github = "fcitx/libime"
use_latest_tag = true

["app-i18n/fcitx"]
source = "github"
github = "fcitx/fcitx5"
use_latest_tag = true

["app-i18n/fcitx-qt"]
source = "github"
github = "fcitx/fcitx5-qt"
use_latest_tag = true

["app-i18n/fcitx-gtk"]
source = "github"
github = "fcitx/fcitx5-gtk"
use_latest_tag = true

["app-i18n/fcitx-lua"]
source = "github"
github = "fcitx/fcitx5-lua"
use_latest_tag = true

["app-i18n/fcitx-configtool"]
source = "github"
github = "fcitx/fcitx5-configtool"
use_latest_tag = true

["app-i18n/fcitx-chinese-addons"]
source = "github"
github = "fcitx/fcitx5-chinese-addons"
use_latest_tag = true

["app-i18n/fcitx-table-extra"]
source = "github"
github = "fcitx/fcitx5-table-extra"
use_latest_tag = true

["app-i18n/fcitx-table-other"]
source = "github"
github = "fcitx/fcitx5-table-other"
use_latest_tag = true

